# Part of `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)
# License: MIT

#group: deprecated-2017Q2
language: generic
sudo: required
#sudo: false
dist: trusty

os:
  - linux
 # - osx

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0
 # matrix:
 #   - LAZ_PKG=true  # Use the latest version from the default package manager
 #   - LAZ_VER=1.6.4

matrix:
  include:
    - os: linux
      env: LAZ_VER=1.6.4  LAZ_ENV=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
    - os: linux
      env: LAZ_VER=1.6.4  LAZ_ENV=wine WINEARCH=win64 LAZ_OPT="--os=win64 --cpu=x86_64"
 #   - os: linux
 #     env: LAZ_VER=1.6.4  LAZ_ENV=qemu-arm LAZ_OPT="--os=linux --cpu=arm"

 # Use https (public access) instead of git for git-submodules. This modifies only Travis-CI behavior!

# disable the default submodule logic
git:
submodules: false

before_install:
  # Start virtual display server
  - Xvfb $DISPLAY &
  - chmod +x .travis.install.py
  # use sed to replace the SSH URL with the public URL, then init and update submodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  # Install prerequisites (fpc/lazarus/wine/qemu)
  - ./.travis.install.py

script:
  - lazbuild --add-package-link ./SimpleBaseLib/src/Packages/FPC/SimpleBaseLib4PascalPackage.lpk  # Add SimpleBaseLib4Pascal Package
  - lazbuild $LAZ_OPT ./SimpleBaseLib/src/Packages/FPC/SimpleBaseLib4PascalPackage.lpk  # Build SimpleBaseLib4Pascal Package
  - lazbuild $LAZ_OPT ./SimpleBaseLib.Tests/FreePascal.Tests/SimpleBaseLibConsole.Tests.lpi               # Build SimpleBaseLib4Pascal Test Project
  - $LAZ_ENV ./SimpleBaseLib.Tests/FreePascal.Tests/bin/SimpleBaseLib --all --format=plain # Run SimpleBaseLib4Pascal TestSuite

notifications:
  email:
    on_success: false
    on_failure: change